site_name: 老闫玩儿技术
nav:
  - 首页: index.md
  - 网络安全:
      - iptables与ufw: 网络安全/iptables与ufw对比.md
  - 网络技术:
      - Wireshark: 网络技术/Wireshark安装使用指南.md
  - 工具:
      - kopia同步: kopia 异地仓库同步.md


#theme: cerulean
#theme: readthedocs

theme:
    name: flatly
#    nav_style: dark

